name: Issue report
description: Report an issue
labels: ["project:"]

body:
  - type: input
    id: title
    attributes:
      label: Issue Title
      description: Please enter the name of a specific view followed by a colon and a little comment.
      placeholder: e.g., ViewName: Brief comment
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue in detail.
    validations:
      required: true

  - type: input
    id: label
    attributes:
      label: Label
      description: Please enter a label starting with "project:"
      placeholder: e.g., project:LabelName
    validations:
      required: true
