name: Issue report
description: Report an issue
labels: ["project:"]

title: "ViewName: Brief comment"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue in detail.
    validations:
      required: true

  - type: dropdown
    id: label
    attributes:
      label: Label
      description: Please select a label.
      options:
        - MDHmeta
        - InsightsMeta
        - EDSCmeta
        - ISMSmeta
        - Other
    validations:
      required: true
