name: Issue report
description: Report an issue
labels: ["project:"]

title: "ViewName: Brief comment"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue in detail.
    validations:
      required: true

  - type: dropdown
    id: label
    attributes:
      label: Label
      description: Please select a label.
      options:
        - label: MDHmeta
        - label: InsightsMeta
        - label: EDSCmeta
        - label: ISMSmeta
        - label: Other
    validations:
      required: true
